---
title: "Introduction to dplyr and ggplot2"
subtitle: "Stat 133, Fall 2017"
author: "Gaston Sanchez"
output: github_document
fontsize: 11pt
urlcolor: blue
---

> ### Learning Objectives:
>
> - Get started with `dplyr`
> - Understand basic verbs
> - Understand the pipe `%>%` operator
> - How to install packages

------

## Manipulating Data Frames

The most common format/structure for a data set is in a tabular format, 
with row and columns. When your data is in this shape, most of the times 
you will work with R data frames (or similar structures).

You need to learn how to manipulate data tables. In the past (before 2014), 
R users manipulated data frames using bracket notation, e.g. `dat[ , ]`,
in order to select specific rows, columns, or cells. This is still possible
and it is a good skill to learn. But nowadays there is an interesting alternative 
for _data wrangling_ provided with the functionality of the package `"dplyr"`.


## Star Wars Data

```{r sw, echo = FALSE}
dat <- read.csv('../data/starwars.csv', stringsAsFactors = FALSE)
```

The data for this lab is in the file `starwars.csv`, which as you may guess, 
contains `r ncol(dat)` variables measured on `r nrow(dat)` famous characters of the Star Wars universe.

To import the data in R you can use the function `read.csv()`:

```{r sw, eval = FALSE}
```

Notice that I'm spcifying the argument `stringsAsFactors = FALSE` to avoid 
the conversion of characters into R factors. Why do you think this is a good 
practice?

All the default reading table functions generate a data frame. Typically, 
everytime I read new data set which I'm not familiar with, or a data set 
that I haven't worked on in a long time, I always like to call a couple of 
functions to inspect its contents:

- `dim()`
- `head()`
- `tail()`
- `str()`
- `summary()`

A first check-up is to examine the dimensions of the data frame with `dim()`:

```{r}
# dimensions (# of rows, # of columns)
dim(dat)
```

If you know in advanced how many rows and columns are in the data table, this 
is a good way to make sure that R was able to read all the records.

Then, depending on the size of the data, you may want to take a peek 
at its contents with `head()` or `tail()`, just to get an idea of what the data 
looks like:

```{r}
# display first few rows
head(dat)
```

For a more detailed description of how R is treating the data type in each 
column, you should use the structure function `str()`

```{r}
# check the structure
str(dat, vec.len = 1)
```

When working with data frames, remember to always take some time inspecting 
the contents, and checking how R is handling the data types. It is in these 
early stages of data exploration that you can catch potential issues in order 
to avoid (disastrous?) consequences or bugs in subsequent stages.

To get information about how R is treating the columns in a data frame 
you can use the function `str()`. This function displays the dimensions of the 
data frame, and then a list with the name of all the 
variables, and their data types (e.g. `chr` character, `num` real, etc). 
The argument `vec.len = 1` indicates that just the first element in each 
column should be displayed.


## Introduction to `"dplyr"`

In order to use the functions in `"dplyr"`, you must load the package first.
Here I'm assuming that you already installed the package. If that's not the 
case the run:

```r
install.packages("dplyr")
```

Remember that you only need to install a package once! After a package has been 
installed in your machine, there is no need to call `install.packages()` again on 
the same package. What you should always invoke in order to use the functions 
in a package is the `library()` function:

```{r warning=FALSE, message=FALSE}
library(dplyr)
```

__About loading packages:__ Another rule to keep in mind is to always load any 
required packages at the very top of your scripts (`.R` or `.Rmd` or `.Rnw` files). 
Avoid calling the `library()` function in the middle of a script. Instead, 
load all the packages before anything else.


### Basic `"dplyr"` verbs

The first _verbs_ to learn about `"dplyr"` are `filter()`, `slice()`, and 
`select()`. Why? Because these are the functions to select a subset of rows 
and columns, which are the most essential type of operations when wrangling data 
frames.

Select rows by position with `slice()`

```{r}
slice(dat, 1:3)
```

Select rows by condition with `filter()`

```{r}
filter(dat, height > 1.9)
```

Select columns by name with `select()`

```{r}
select(dat, name, height)
```


### Your turn:

- subset the data by selecting the last 5 rows
- select those individuals with height less than 1.6 meters tall, and of human species
- of those individuals that are human, select their names and jedi status
- display the names of jedis


## Your Turn

Use functions in `"dplyr"` to answer the following questions:

- What's the largest height value?

- What's the minimum height value?

- What's the overall average height?

- Who has the smallest height?

- Who has the largest height?

- What are the unique weapons?

- How many different species?

- Who is the individual with the shortest height?

- Are there any subjects with weapon "knife"? If so how many and who are they?

- Are there any subjects with height > 2 meters? If so how many and who are they?


### Sorting

- Obtain height values in increasing order

- Obtain weight values in decreasing order

- Sort data by height in increasing order

- Sort data by weight in decreasing order

- Sort data by gender in increasing order

- Sort data by species in increasing order


-----

```{r}
# =====================================================
# Subsetting operations
# =====================================================

# create a data frame `han` with Han Solo's information (i.e. row)


# create a data frame `males` with the data of male subjects


# get the data for those subjects 
# with height less than 1.7 


# get the data for subjects with 
# height less than 1.7 and weight less than 50


# create a data frame `droids_humans` with the data of droids or humans


# create a data frame `non_humans` with the data of non-humans


#
```


-----

```{r}
# =====================================================
# More Wrangling
# =====================================================

# get the data of those above the average weight?


# how many unarmed humans?


# standard deviation of weight in non-humans 


# which humans use a lightsaber


# median height of unarmed non-humans


# get the square weight of non-jedis


# get the log of height for subjects
# with blaster or bowcaster weapons


# create a new variable "newvar": height divided by weight


# add 'newvar' to the data frame sw


#
```


-----


## Solutions

```{r}
# selecting the last 5 rows
slice(dat, 15:20)

# individuals with height < 1.6, and of human species
filter(dat, height < 1.6 & species == "human")

# display names and jedi status of humans
humans <- filter(dat, species == "human")
select(humans, name, jedi)

# display the names of jedis
jedis <- filter(dat, jedi == "yes_jedi")
select(jedis, name)
```
